name: Validate Project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Echo current actor
        run: echo 'Current user is:' $GITHUB_ACTOR

      - name: Build with Gradle
        run: ./gradlew check --info --stacktrace

      - name: Publish test result artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/allTests